 const userActionTypes ={
    SET_CURRENT_USER :'SET_CURRENT_USER',
    GOOGLE_SIGN_IN_REQUEST : 'GOOGLE_SIGN_IN_REQUEST',
    GOOGLE_SIGN_IN_SUCCESS :'GOOGLE_SIGN_IN_SUCCESS',
    GOOGLE_SIGN_IN_FAILURE : 'GOOGLE_SIGN_IN_FAILURE',
    EMAIL_SIGN_IN_REQUEST : 'EMAIL_SIGN_IN_REQUEST',
    EMAIL_SIGN_IN_SUCCESS :'EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_FAILURE : 'EMAIL_SIGN_IN_FAILURE'
}

export default userActionTypes;